version: "3.8"

services:
  app:
    build: .
    #container_name: bengkel-app
    restart: always
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: bengkel_mobil
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - uji-net

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: bengkel_mobil
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - uji-net

  nginx:
    image: nginx:latest
    container_name: nginx-web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl/bengkel.crt:/etc/nginx/ssl/bengkel.crt:ro
      - ./ssl/bengkel.key:/etc/nginx/ssl/bengkel.key:ro
    networks:
       - uji-net

networks:
  uji-net:
    driver: bridge

volumes:
  dbdata: 